version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.0.5

jobs:
  test_core:
    docker:
    - image: maven:3.6-jdk-8-slim
    steps:
    - checkout
    - run: mvn --projects core test

  test_ingestion:
    docker:
    - image: maven:3.6-jdk-8-slim
    steps:
    - checkout
    - run: mvn --projects ingestion test

  test_serving:
    docker:
    - image: maven:3.6-jdk-8-slim
    steps:
    - checkout
    - run: mvn --projects serving test

  test_cli:
    docker:
    - image: golang:1.12
    steps:
    - checkout
    - run: go test ./cli/feast/...

  build_core:
    docker:
    - image: google/cloud-sdk:245.0.0
    steps:
    - checkout
    - setup_remote_docker
    - run: echo ${GCLOUD_SERVICE_KEY} | gcloud auth activate-service-account --key-file=-
    - run: gcloud auth configure-docker
    - run: docker build -t us.gcr.io/kf-feast/feast-core:${CIRCLE_SHA1} -f Dockerfiles/core/Dockerfile .
    - run: docker push us.gcr.io/kf-feast/feast-core:${CIRCLE_SHA1}


workflows:
  version: 2.1
  feast_ci:
    jobs:
    # - test_core
    # - test_ingestion
    # - test_serving
    # - test_cli
    - build_core
