version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.0.5

jobs:
  test_core:
    docker:
    - image: maven:3.6-jdk-8-slim
    steps:
    - checkout
    - run: mvn --projects core test

  test_ingestion:
    docker:
    - image: maven:3.6-jdk-8-slim
    steps:
    - checkout
    - run: mvn --projects ingestion test

  test_serving:
    docker:
    - image: maven:3.6-jdk-8-slim
    steps:
    - checkout
    - run: mvn --projects serving test

  test_cli:
    docker:
    - image: golang:1.12
    steps:
    - checkout
    - run: go test ./cli/feast/...

  build_core:


workflows:
  version: 2.1
  feast_ci:
    jobs:
    # - test_core
    # - test_ingestion
    # - test_serving
    # - test_cli
    - gcp-gcr/build_and_push_core:
        image: feast-core
        registry-url: us.gcr.io
        tag: ${CIRCLE_SHA1}
